---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en,de-DE
import:
  - "@cspell/dict-de-de/cspell-ext.json"
useGitignore: true
dictionaryDefinitions:
  - name: project-words
    path: "./cspell.words.txt"
    addWords: true
dictionaries:
  - project-words

ignorePaths:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/.next/**"
  - "**/out/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/playwright-report/**"
  - "**/public/**"
  - "**/prisma/migrations/**"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
  - "**/yarn.lock"
  - "**/.turbo/**"
  - "**/.vercel/**"
  - "/cspell.words.txt"
